
##################################
#      SkyDonatePlugin v2.0      #
#       panel.skydonate.ru       #
#     t.me/skydonate_support     #
#         Dev by n1zamu          #
##################################

####### НАСТРОЙКА ПЛАГИНА #######

# Находится во вкладке Сервера (Панель -> Ваш магазин -> Товары -> Сервера)
SERVER_ID: 0

# Находится в URL (ссылке) (Например: https://panel.skydonate.ru/store/0/ - 0 в данном случае - то, что нам нужно) У ВАС БУДЕТ ДРУГОЕ ЗНАЧЕНИЕ
STORE_ID: 0

# Находите в панеле во вкладке вашего магазина (Раздел "Настройки выдачи")
SECRET_KEY: NONE

# Подробный вывод ошибок и действий плагина в консоль.
debug: true

####### НАСТРОЙКА ДОПЛАТЫ #######

# Группы LuckPerms которые будут учавствовать в доплате.
group:
  # Группа: айди продукта с секции products
  # Работает только для товаров с типом "Привилегия (Доплата)"
  vip: id1
  default: id2

####### НАСТРОЙКА ВЫДАЧИ #######

# Команды выдачи товаров
# Плейсхолдеры:
# Ник покупателя - {player}
# Количество (Для типа "Валюта") - {amount}
# Титул (Для типа "Титул") - {title}
# Айди товаров вы можете найти на карточке каждого товара в строке ID
products:
  id1: # ID товара
    actions:
      - "broadcast Игрок {player} купил донат!"
  id4:
    actions:
      - "broadcast Игрок {player} купил {title}!"
  id5:
    actions:
      - "broadcast Игрок {player} купил {amount} валюты!"
      - "eco give {player} {amount}"